### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by dodona2** [arnoldrobbins/mcilroy-regex#7]
using **gcc (GCC) 9.2.1** 20190827 (Red Hat 9.2.1-1) under **fedoro31**:

g++ -I. -O2 -std=c++11 -g -DDEBUG -c re1.cpp
g++ -I. -O2 -std=c++11 -g -DDEBUG -c re2.cpp
g++ -I. -O2 -std=c++11 -g -DDEBUG -c grep.cpp
g++ -I. -O2 -std=c++11 -g -DDEBUG -o grep grep.o re[12].o
g++ -I. -O2 -std=c++11 -g -DDEBUG -c sed0.cpp
g++ -I. -O2 -std=c++11 -g -DDEBUG -c sed1.cpp
g++ -I. -O2 -std=c++11 -g -DDEBUG -c sed2.cpp
g++ -I. -O2 -std=c++11 -g -DDEBUG -c sed3.cpp
g++ -I. -O2 -std=c++11 -g -DDEBUG sed[0123].o re1.o re2.o -o sed
**s**ed error: bad regular expression: s/^ *[0-9]\+ *//****

**check the newly build sed:**
$ echo 012abc|sed 's/^ .*[0-9]\+ .*//g'
sed error: bad regular expression: s/^ .*[0-9]\+ .*//g
sed error: bad regular expression: s/^ *[0-9]\+ *//

**against gnu sed:**
$ echo 012abc|sed 's/^ .*[0-9]\+ .*//g'
012abc

**shows that something wrong with regexp(sed).**

needless to say that replacing faulty sed by gnu sed let make do its job without errors

**Comment by arnoldrobbins** [comment]
You have "." in your search path.  McIlroy's `sed` doesn't accept the same patterns as the GNU versions do.  Build without "." in your search path and you won't have any problems.

**Comment by dodona2** [comment]
thanks Arnold.
